---
Name: jellygnite-elements
---
DNADesign\Elemental\Extensions\ElementalAreasExtension:
  keep_content_fields: true
  stop_element_inheritance: false
DNADesign\Elemental\Models\BaseElement:
  extensions:
    - Jellygnite\Elements\Extensions\BaseElementExtension
Jellygnite\Elements\Model\BaseElementObject:
  extensions:
    - Jellygnite\ElementalStyle\Extensions\DynamicStyleExtension
DNADesign\Elemental\Models\ElementContent:
  extensions:
    - Jellygnite\Elements\Extensions\ElementContentExtension


